/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations.index'
import { Route as ResourcesNewRouteImport } from './routes/resources.new'
import { Route as ReservationsNewRouteImport } from './routes/reservations.new'
import { Route as ResourcesIdEditRouteImport } from './routes/resources.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesNewRoute = ResourcesNewRouteImport.update({
  id: '/resources/new',
  path: '/resources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsNewRoute = ReservationsNewRouteImport.update({
  id: '/reservations/new',
  path: '/reservations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdEditRoute = ResourcesIdEditRouteImport.update({
  id: '/resources/$id/edit',
  path: '/resources/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/reservations': typeof ReservationsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/reservations/new'
    | '/resources/new'
    | '/reservations/'
    | '/resources/'
    | '/resources/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/reservations/new'
    | '/resources/new'
    | '/reservations'
    | '/resources'
    | '/resources/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/reservations/new'
    | '/resources/new'
    | '/reservations/'
    | '/resources/'
    | '/resources/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReservationsNewRoute: typeof ReservationsNewRoute
  ResourcesNewRoute: typeof ResourcesNewRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ResourcesIdEditRoute: typeof ResourcesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/new': {
      id: '/resources/new'
      path: '/resources/new'
      fullPath: '/resources/new'
      preLoaderRoute: typeof ResourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/new': {
      id: '/reservations/new'
      path: '/reservations/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof ReservationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id/edit': {
      id: '/resources/$id/edit'
      path: '/resources/$id/edit'
      fullPath: '/resources/$id/edit'
      preLoaderRoute: typeof ResourcesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReservationsNewRoute: ReservationsNewRoute,
  ResourcesNewRoute: ResourcesNewRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ResourcesIdEditRoute: ResourcesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
